module.exports = [
  'firm',
  'slightly irregular',
  'industrial-strength',
  'cat-friendly',
  'chewy',
  'odorless',
  'economy',
  'deluxe kind',
  'family-size',
  'travel size',
  'shatterproof',
  'refurbished',
  'professional-quality',
  'rechargeable',
  'women\'s',
  'children\'s',
  'men\'s',
  'inflatable',
  'flame retardant',
  'homeopathic',
  'natural',
  'gluten-free',
  'all-wheel drive',
  'hypo-allergenic',
  'convertible',
  'unflavored',
  'special edition',
  'individually wrapped',
  'solid state',
  'Brooklyn-style',
  'elastic waist',
  'high-performance',
  'uncut',
  'bake-n-serve',
  'vegan',
  'fully articulated',
  'blue',
  'vintage',
  'locally grown',
  'petite',
  'fully automatic',
  'lemon scented',
  'free-range',
  'assorted',
  'fleece lined',
  'wi-fi ready',
  'four color',
  'five pocket',
  'extended release',
  'basic',
  'professional',
  'chewable',
  'salted caramel',
  'aerosol',
  'original formula',
  'gentle',
  'complete',
  'extra pulp',
  'washable',
  'oil free',
  'indoor',
  'Swedish',
  'soft',
  'hardcore',
  'vat-grown',
  'plain',
  'hand-cut',
  'new-to-you',
  'sexy',
  'fun-size',
  'pumpkin spice'
];
